import { useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'

import { useAuth } from '../features/auth/auth-context'
import { apiRequest } from '../lib/api'
import { fetchFavorites, createFavorite, deleteFavorite } from '../lib/favorites'
import { type UploadedImage } from '../lib/upload'
import { ImageUploader } from '../components/ImageUploader'
import { RichEditor } from '../components/RichEditor'
import { useItalianComuni, searchComuni, getProvinces, getProvinceName, getProvinceSigla } from '../lib/italian-comuni'
import { ConfirmModal } from '../components/ConfirmModal'
import { MapPicker } from '../components/MapPicker'
import type { ComuneEntry } from '../lib/italian-comuni'
import styles from './EventsPage.module.scss'

type EventItem = {
  id: string
  name: string
  location: {
    label: string
    addressLine1: string | null
    addressLine2: string | null
    city: string | null
    province: string | null
    region: string | null
    country: string | null
    postalCode: string | null
    coordinates: { type: string; coordinates: [number, number] } | null
    googleMapsUrl: string | null
  }
  startDate: string
  endDate: string
  currencyName: string
  url: string | null
  shortDescription: string | null
  longDescription: string | null
  coverImage: UploadedImage | null
  logo: UploadedImage | null
  gallery: UploadedImage[]
  themeBrand: string | null
  themeText: string | null
  themeSurface: string | null
  themeHighlight: string | null
  cashPaymentsEnabled: boolean
  createdAt: string
  updatedAt: string
}

type EventFormData = {
  name: string
  locationLabel: string
  addressLine1: string
  addressLine2: string
  city: string
  province: string
  region: string
  country: string
  postalCode: string
  latitude: string
  longitude: string
  googleMapsUrl: string
  startDate: string
  endDate: string
  currencyName: string
  url: string
  shortDescription: string
  longDescription: string
  coverImage: UploadedImage | null
  logo: UploadedImage | null
  gallery: UploadedImage[]
  themeBrand: string
  themeText: string
  themeSurface: string
  themeHighlight: string
  cashPaymentsEnabled: boolean
}

const emptyForm: EventFormData = {
  name: '',
  locationLabel: '',
  addressLine1: '',
  addressLine2: '',
  city: '',
  province: '',
  region: '',
  country: 'ITA',
  postalCode: '',
  latitude: '',
  longitude: '',
  googleMapsUrl: '',
  startDate: '',
  endDate: '',
  currencyName: '',
  url: '',
  shortDescription: '',
  longDescription: '',
  coverImage: null,
  logo: null,
  gallery: [],
  themeBrand: '',
  themeText: '',
  themeSurface: '',
  themeHighlight: '',
  cashPaymentsEnabled: true,
}

type StandItem = {
  id: string
  name: string
  eventIds: string[]
  locations?: Array<{ eventId: string; location: unknown }>
}

export function EventsPage() {
  const { user } = useAuth()
  const [events, setEvents] = useState<EventItem[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [showForm, setShowForm] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [form, setForm] = useState<EventFormData>(emptyForm)
  const [favoriteIds, setFavoriteIds] = useState<Set<string>>(new Set())
  const [favMap, setFavMap] = useState<Map<string, string>>(new Map())
  const [standList, setStandList] = useState<StandItem[]>([])
  const [expandedEventId, setExpandedEventId] = useState<string | null>(null)
  const [savingStands, setSavingStands] = useState<Set<string>>(new Set())
  const [urlEditMode, setUrlEditMode] = useState(false)
  const [alertMsg, setAlertMsg] = useState<string | null>(null)
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null)
  const comuni = useItalianComuni()
  const [cityQuery, setCityQuery] = useState('')
  const [citySuggestions, setCitySuggestions] = useState<ComuneEntry[]>([])
  const [showCitySuggestions, setShowCitySuggestions] = useState(false)
  const [cityFocused, setCityFocused] = useState(false)
  const selectingSuggestion = useRef(false)
  const mountedRef = useRef(true)

  const autoGeneratedUrl = useMemo(() => {
    if (form.latitude && form.longitude) {
      return `https://www.google.com/maps/?q=${form.latitude},${form.longitude}`
    }
    if (form.addressLine1.trim()) {
      return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(form.addressLine1)}`
    }
    if (form.city.trim()) {
      return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(form.city)}`
    }
    return ''
  }, [form.addressLine1, form.latitude, form.longitude, form.city])

  const handleCityQueryChange = (value: string) => {
    setCityQuery(value)
    setForm((prev) => ({ ...prev, city: value }))
    if (!comuni.isLoaded) return
    const suggestions = searchComuni(value, comuni.selectedRegion || undefined, comuni.selectedProvince || undefined)
    setCitySuggestions(suggestions)
    setShowCitySuggestions(true)
  }

  const handleCitySelect = (entry: ComuneEntry) => {
    setForm((prev) => ({
      ...prev,
      city: entry.name,
      province: entry.province,
      region: entry.region,
    }))
    comuni.setRegionAndProvince(entry.region, entry.province)
    setCityQuery(entry.name)
    setShowCitySuggestions(false)
    setCitySuggestions([])
  }

  const handleRegionChange = (region: string) => {
    comuni.setSelectedRegion(region)
    setForm((prev) => ({
      ...prev,
      region,
      province: '',
      city: '',
    }))
    setCityQuery('')
    setCitySuggestions([])
  }

  const handleProvinceChange = (province: string) => {
    comuni.setSelectedProvince(province)
    setForm((prev) => ({
      ...prev,
      province,
      city: '',
    }))
    setCityQuery('')
    setCitySuggestions([])
  }

  const fetchEvents = async () => {
    try {
      const data = await apiRequest<{ items: EventItem[] }>('/events')
      if (!mountedRef.current) return
      let items = data.items
      if (user?.isPlatformAdmin === false && user?.adminEventIds && user.adminEventIds.length > 0) {
        items = items.filter((ev) => user.adminEventIds!.includes(ev.id))
      }
      setEvents(items)
    } catch { /* not required */ }
    finally {
      if (mountedRef.current) setIsLoading(false)
    }
  }

  const fetchFavs = async () => {
    try {
      const data = await fetchFavorites()
      const ids = new Set<string>()
      const map = new Map<string, string>()
      for (const fav of data.items) {
        if (fav.event) {
          ids.add(fav.event.id)
          map.set(fav.event.id, fav.id)
        }
      }
      setFavoriteIds(ids)
      setFavMap(map)
    } catch { /* not required */ }
  }

  const fetchStands = async () => {
    try {
      const data = await apiRequest<{ items: StandItem[] }>('/stands')
      setStandList(data.items)
    } catch { /* not required */ }
  }

  useEffect(() => {
    mountedRef.current = true
    fetchEvents()
    fetchFavs()
    fetchStands()
    return () => { mountedRef.current = false }
  }, [])

  const toggleFavorite = async (eventId: string) => {
    if (favoriteIds.has(eventId)) {
      const favId = favMap.get(eventId)
      if (favId) {
        await deleteFavorite(favId)
        setFavoriteIds((prev) => { const next = new Set(prev); next.delete(eventId); return next })
        setFavMap((prev) => { const next = new Map(prev); next.delete(eventId); return next })
      }
    } else {
      const data = await createFavorite({ eventId })
      setFavoriteIds((prev) => { const next = new Set(prev); next.add(eventId); return next })
      setFavMap((prev) => { const next = new Map(prev); next.set(eventId, data.item.id); return next })
    }
  }

  const handleToggleStand = async (standId: string, eventId: string, currentlyLinked: boolean) => {
    setSavingStands((prev) => { const next = new Set(prev); next.add(standId); return next })
    try {
      const stand = standList.find((s) => s.id === standId)
      if (!stand) return
      const newEventIds = currentlyLinked
        ? stand.eventIds.filter((id) => id !== eventId)
        : [...stand.eventIds, eventId]

      const body: Record<string, unknown> = { eventIds: newEventIds }

      // Sync locations when adding an event
      if (!currentlyLinked) {
        const locations = [...(stand.locations ?? [])]
        if (!locations.some((l) => l.eventId === eventId)) {
          locations.push({ eventId, location: null })
        }
        body.locations = locations
      }

      await apiRequest(`/stands/${standId}`, {
        method: 'PATCH',
        bodyJson: body,
      })
      setStandList((prev) =>
        prev.map((s) => (s.id === standId ? { ...s, eventIds: newEventIds } : s))
      )
    } catch { /* not required */ }
    finally {
      setSavingStands((prev) => { const next = new Set(prev); next.delete(standId); return next })
    }
  }

  const openCreate = () => {
    setForm({ ...emptyForm, country: 'ITA' })
    setEditingId(null)
    setUrlEditMode(false)
    setShowForm(true)
    comuni.reset()
    setCityQuery('')
    setCitySuggestions([])
    setShowCitySuggestions(false)
  }

  const normalizeCountry = (c: string | null | undefined): string => {
    if (!c) return 'ITA'
    const upper = c.toUpperCase().trim()
    if (upper === 'ITALIA' || upper === 'ITALY' || upper === 'IT') return 'ITA'
    return c
  }

  const openEdit = (ev: EventItem) => {
    setUrlEditMode(false)
    setForm({
      name: ev.name,
      locationLabel: ev.location.label,
      addressLine1: ev.location.addressLine1 ?? '',
      addressLine2: ev.location.addressLine2 ?? '',
      city: ev.location.city ?? '',
      province: getProvinceSigla(ev.location.province ?? '') || ev.location.province || '',
      region: ev.location.region ?? '',
      country: normalizeCountry(ev.location.country),
      postalCode: ev.location.postalCode ?? '',
      latitude: ev.location.coordinates ? String(ev.location.coordinates.coordinates[1] ?? '') : '',
      longitude: ev.location.coordinates ? String(ev.location.coordinates.coordinates[0] ?? '') : '',
      googleMapsUrl: ev.location.googleMapsUrl ?? '',
      startDate: ev.startDate.slice(0, 10),
      endDate: ev.endDate.slice(0, 10),
      currencyName: ev.currencyName,
      url: ev.url ?? '',
      shortDescription: ev.shortDescription ?? '',
      longDescription: ev.longDescription ?? '',
      coverImage: ev.coverImage,
      logo: ev.logo,
      gallery: ev.gallery,
      themeBrand: ev.themeBrand ?? '',
      themeText: ev.themeText ?? '',
      themeSurface: ev.themeSurface ?? '',
      themeHighlight: ev.themeHighlight ?? '',
      cashPaymentsEnabled: ev.cashPaymentsEnabled,
    })
    setEditingId(ev.id)
    setShowForm(true)
    setCityQuery(ev.location.city ?? '')
    setCitySuggestions([])
    setShowCitySuggestions(false)
    if (ev.location.region && ev.location.province) {
      comuni.setRegionAndProvince(ev.location.region, ev.location.province)
    } else if (ev.location.region) {
      comuni.setSelectedRegion(ev.location.region)
    }
  }

  const handleSubmit = async () => {
    const bodyJson = {
      name: form.name,
      location: {
        label: form.locationLabel,
        addressLine1: form.addressLine1 || null,
        addressLine2: form.addressLine2 || null,
        city: form.city || null,
        province: form.province || null,
        region: form.region || null,
        country: form.country || null,
        postalCode: form.postalCode || null,
        coordinates: form.latitude && form.longitude
          ? {
              type: 'Point',
              coordinates: [
                Number(form.longitude),
                Number(form.latitude),
              ],
            }
          : null,
        googleMapsUrl: form.googleMapsUrl || autoGeneratedUrl || null,
      },
      startDate: form.startDate,
      endDate: form.endDate,
      currencyName: form.currencyName,
      url: form.url || null,
      shortDescription: form.shortDescription || null,
      longDescription: form.longDescription || null,
      coverImage: form.coverImage,
      logo: form.logo,
      gallery: form.gallery,
      themeBrand: form.themeBrand || null,
      themeText: form.themeText || null,
      themeSurface: form.themeSurface || null,
      themeHighlight: form.themeHighlight || null,
      cashPaymentsEnabled: form.cashPaymentsEnabled,
    }

    if (editingId) {
      await apiRequest(`/events/${editingId}`, {
        method: 'PATCH',
        bodyJson,
      })
    } else {
      await apiRequest('/events', {
        method: 'POST',
        bodyJson,
      })
    }

    setShowForm(false)
    setEditingId(null)
    setForm(emptyForm)
    await fetchEvents()
  }

  const handleDelete = async () => {
    if (!deleteConfirmId) return
    const id = deleteConfirmId
    setDeleteConfirmId(null)
    try {
      await apiRequest(`/events/${id}`, { method: 'DELETE' })
      if (mountedRef.current) await fetchEvents()
    } catch { /* not required */ }
  }

  const fillFromNominatim = async (lat: string, lng: string) => {
    try {
      const res = await fetch(
        `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lng}&addressdetails=1&accept-language=it`
      )
      if (!res.ok) return
      const data = await res.json()
      if (!data?.address) return

      const a = data.address
      const fullProvince = (a.county || a.state || '')
        .replace(/^Provincia\s+(di|dell'|della|del)\s+/i, '')
        .replace(/^Città\s+Metropolitana\s+(di|dell'|della|del)\s+/i, '')
        .replace(/^Libero\s+Consorzio\s+Comunale\s+(di|dell'|della|del)\s+/i, '')
        .trim()
      setForm((prev) => ({
        ...prev,
        city: a.city || a.town || a.village || a.municipality || prev.city,
        province: getProvinceSigla(fullProvince) || fullProvince || prev.province,
        region: a.region || prev.region,
        country: a.country || prev.country,
        postalCode: a.postcode || prev.postalCode,
      }))
    } catch {
      // Nominatim fallito — lat/lng già inserite
    }
  }

  const handleGeolocate = () => {
    if (!navigator.geolocation) {
      setAlertMsg('Geolocalizzazione non supportata dal browser.')
      return
    }

    navigator.geolocation.getCurrentPosition(
      (pos) => {
        const lat = String(pos.coords.latitude)
        const lng = String(pos.coords.longitude)
        setForm((prev) => ({
          ...prev,
          latitude: lat,
          longitude: lng,
        }))
        fillFromNominatim(lat, lng)
      },
      (err) => {
        setAlertMsg(`Impossibile rilevare la posizione: ${err.message}`)
      },
      { enableHighAccuracy: true, timeout: 10000 }
    )
  }

  const fmtDate = (iso: string) => new Date(iso).toLocaleDateString('it-IT')

  if (isLoading) return null

  return (
    <div className={styles.page}>
      <div className="page-shell">
        <div className={styles.header}>
          <div>
            <a href="/dashboard" className={styles.backLink}>&larr; Dashboard</a>
            <span className="eyebrow">Gestione</span>
            <h1 className={styles.title}>Eventi</h1>
          </div>
          <button className={styles.primaryBtn} onClick={openCreate}>
            Nuovo evento
          </button>
        </div>

        {showForm && (
          <form className={styles.form} onSubmit={(e) => { e.preventDefault(); handleSubmit() }}>
            <fieldset className={styles.fieldset}>
              <legend className={styles.legend}>Informazioni base</legend>
              <div className={styles.field}>
                <label htmlFor="ev-name">Nome *</label>
                <input id="ev-name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required />
              </div>
              <div className={styles.fieldRow}>
                <div className={styles.field}>
                  <label htmlFor="ev-start">Data inizio *</label>
                  <input id="ev-start" type="date" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} required />
                </div>
                <div className={styles.field}>
                  <label htmlFor="ev-end">Data fine *</label>
                  <input id="ev-end" type="date" value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} required />
                </div>
              </div>
              <div className={styles.field}>
                <label htmlFor="ev-currency">Nome moneta evento *</label>
                <input id="ev-currency" value={form.currencyName} onChange={(e) => setForm({ ...form, currencyName: e.target.value })} placeholder="es. StreetCoin" required />
              </div>
              <div className={styles.field}>
                <label htmlFor="ev-url">Sito ufficiale</label>
                <input id="ev-url" type="url" value={form.url} onChange={(e) => setForm({ ...form, url: e.target.value })} placeholder="https://..." />
              </div>
              <div className={styles.checkField}>
                <label className={styles.checkLabel}>
                  <input
                    type="checkbox"
                    checked={form.cashPaymentsEnabled}
                    onChange={(e) => setForm({ ...form, cashPaymentsEnabled: e.target.checked })}
                  />
                  <span>Pagamenti in contanti abilitati</span>
                </label>
                <p className={styles.fieldHint}>
                  Se disabilitato, tutti i pagamenti dovranno avvenire tramite crediti evento.
                </p>
              </div>
            </fieldset>

            <fieldset className={styles.fieldset}>
              <legend className={styles.legend}>Luogo</legend>
              <div className={styles.field}>
                <label htmlFor="ev-loc-label">Etichetta *</label>
                <input id="ev-loc-label" value={form.locationLabel} onChange={(e) => setForm({ ...form, locationLabel: e.target.value })} placeholder="es. Piazza Centrale" required />
              </div>
              <div className={styles.field}>
                <label htmlFor="ev-addr1">Indirizzo</label>
                <input id="ev-addr1" value={form.addressLine1} onChange={(e) => setForm({ ...form, addressLine1: e.target.value })} />
              </div>
              <div className={styles.field}>
                <label htmlFor="ev-addr2">Indirizzo (riga 2)</label>
                <input id="ev-addr2" value={form.addressLine2} onChange={(e) => setForm({ ...form, addressLine2: e.target.value })} />
              </div>
              <div className={styles.fieldRow}>
                <div className={styles.field} style={{ maxWidth: '8rem' }}>
                  <label htmlFor="ev-country">Paese</label>
                  <input id="ev-country" value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })} maxLength={3} />
                </div>
              </div>

              {comuni.isLoaded ? (
                <>
                  <div className={styles.fieldRow}>
                    <div className={styles.field}>
                      <label htmlFor="ev-region">Regione</label>
                      <select
                        id="ev-region"
                        value={form.region}
                        onChange={(e) => handleRegionChange(e.target.value)}
                        disabled={form.country !== 'ITA'}
                      >
                        <option value="">— Seleziona —</option>
                        {comuni.regions.map((r) => (
                          <option key={r} value={r}>{r}</option>
                        ))}
                      </select>
                    </div>
                    <div className={styles.field}>
                      <label htmlFor="ev-province">Provincia</label>
                      <select
                        id="ev-province"
                        value={form.province}
                        onChange={(e) => handleProvinceChange(e.target.value)}
                        disabled={form.country !== 'ITA' || !form.region}
                      >
                        <option value="">— Seleziona —</option>
                        {getProvinces(form.region).map((p) => (
                          <option key={p} value={p}>{getProvinceName(p)}</option>
                        ))}
                      </select>
                    </div>
                  </div>
                  <div className={styles.field} style={{ position: 'relative' }}>
                    <label htmlFor="ev-city">Città</label>
                    <input
                      id="ev-city"
                      value={cityQuery}
                      onChange={(e) => handleCityQueryChange(e.target.value)}
                      onFocus={() => { setCityFocused(true); if (citySuggestions.length) setShowCitySuggestions(true) }}
                      onBlur={() => setTimeout(() => {
                        setCityFocused(false)
                        setShowCitySuggestions(false)
                        if (selectingSuggestion.current) { selectingSuggestion.current = false; return }
                        if (!comuni.isLoaded || !cityQuery) return
                        if (cityQuery === form.city) return
                        const matches = searchComuni(cityQuery, comuni.selectedRegion || undefined, comuni.selectedProvince || undefined)
                        const exact = matches.find((m) => m.name.toLowerCase() === cityQuery.toLowerCase())
                        if (exact) handleCitySelect(exact)
                      }, 200)}
                      placeholder="Digita per cercare un comune..."
                      disabled={form.country !== 'ITA'}
                    />
                    {showCitySuggestions && cityFocused && citySuggestions.length > 0 && (
                      <ul style={{
                        position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 10,
                        background: '#fff', border: '1px solid #ccc', borderRadius: '4px',
                        maxHeight: '200px', overflowY: 'auto', listStyle: 'none',
                        margin: '2px 0 0', padding: '4px 0',
                      }}>
                        {citySuggestions.map((entry) => (
                          <li
                            key={`${entry.name}-${entry.province}`}
                            onMouseDown={() => { selectingSuggestion.current = true; handleCitySelect(entry) }}
                            style={{
                              padding: '6px 12px', cursor: 'pointer',
                              display: 'flex', justifyContent: 'space-between', gap: '1rem',
                            }}
                            onMouseEnter={(e) => (e.currentTarget.style.background = '#f0f0f0')}
                            onMouseLeave={(e) => (e.currentTarget.style.background = '')}
                          >
                            <span>{entry.name}</span>
                            <span style={{ color: '#888', fontSize: '0.85rem' }}>
                               {getProvinceName(entry.province)} ({entry.region})
                            </span>
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                </>
              ) : (
                <div className={styles.fieldRow}>
                  <div className={styles.field}>
                    <label htmlFor="ev-city">Città</label>
                    <input id="ev-city" value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} />
                  </div>
                  <div className={styles.field}>
                    <label htmlFor="ev-province">Provincia</label>
                    <input id="ev-province" value={form.province} onChange={(e) => setForm({ ...form, province: e.target.value })} />
                  </div>
                </div>
              )}
              <div className={styles.field}>
                <label htmlFor="ev-postal">CAP</label>
                <input id="ev-postal" value={form.postalCode} onChange={(e) => setForm({ ...form, postalCode: e.target.value })} />
              </div>
              <div className={styles.field}>
                <label>Posizione</label>
                <MapPicker
                  lat={form.latitude}
                  lng={form.longitude}
                  onChange={(lat, lng) => setForm((prev) => ({ ...prev, latitude: lat, longitude: lng }))}
                  height="200px"
                />
                <button type="button" className={styles.secondaryBtn} onClick={handleGeolocate} style={{ fontSize: '0.85rem', padding: '0.4rem 0.75rem', marginTop: '0.35rem' }}>
                  📍 Rileva posizione
                </button>
              </div>
              <div className={styles.field}>
                <label htmlFor="ev-maps">URL Google Maps</label>
                <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
                  <input
                    id="ev-maps"
                    value={form.googleMapsUrl}
                    readOnly={!urlEditMode}
                    onChange={(e) => setForm({ ...form, googleMapsUrl: e.target.value })}
                    style={{ flex: 1 }}
                  />
                  {urlEditMode ? (
                    <>
                      <button type="button" className={styles.textBtn} onClick={() => { setForm({ ...form, googleMapsUrl: autoGeneratedUrl }) }}>
                        🔁 Rigenera
                      </button>
                      <button type="button" className={styles.textBtn} onClick={() => setUrlEditMode(false)}>
                        ✅ Fine modifica
                      </button>
                    </>
                  ) : (
                    <button type="button" className={styles.textBtn} onClick={() => setUrlEditMode(true)}>
                      ✏️ Modifica
                    </button>
                  )}
                  <a
                    href={form.googleMapsUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={styles.textBtn}
                    style={{ textDecoration: 'none' }}
                    onClick={(e) => { if (!form.googleMapsUrl) e.preventDefault() }}
                  >
                    🗺️ Vedi su GMaps
                  </a>
                </div>
              </div>
            </fieldset>

            <fieldset className={styles.fieldset}>
              <legend className={styles.legend}>Descrizione</legend>
              <div className={styles.field}>
                <label htmlFor="ev-short">Descrizione breve</label>
                <RichEditor
                  value={form.shortDescription}
                  onChange={(html) => setForm({ ...form, shortDescription: html })}
                  placeholder="Breve descrizione dell'evento..."
                  maxLength={500}
                />
              </div>
              <div className={styles.field}>
                <label htmlFor="ev-long">Descrizione lunga</label>
                <RichEditor
                  value={form.longDescription}
                  onChange={(html) => setForm({ ...form, longDescription: html })}
                  placeholder="Descrizione completa con formattazione..."
                />
              </div>
            </fieldset>

            <fieldset className={styles.fieldset}>
              <legend className={styles.legend}>Tema personalizzato</legend>
              <p className={styles.fieldHint}>Lascia vuoto per usare il tema stagionale di default.</p>
              <div className={styles.themeGrid}>
                <div className={styles.field}>
                  <label htmlFor="ev-theme-brand">Colore principale</label>
                  <div className={styles.colorRow}>
                    <input id="ev-theme-brand" type="color" value={form.themeBrand || '#bf5a2a'} onChange={(e) => setForm({ ...form, themeBrand: e.target.value === '#bf5a2a' ? '' : e.target.value })} />
                    <input value={form.themeBrand} onChange={(e) => setForm({ ...form, themeBrand: e.target.value })} placeholder="#bf5a2a" />
                  </div>
                </div>
                <div className={styles.field}>
                  <label htmlFor="ev-theme-text">Colore testo</label>
                  <div className={styles.colorRow}>
                    <input id="ev-theme-text" type="color" value={form.themeText || '#14261f'} onChange={(e) => setForm({ ...form, themeText: e.target.value === '#14261f' ? '' : e.target.value })} />
                    <input value={form.themeText} onChange={(e) => setForm({ ...form, themeText: e.target.value })} placeholder="#14261f" />
                  </div>
                </div>
                <div className={styles.field}>
                  <label htmlFor="ev-theme-surface">Colore sfondo</label>
                  <div className={styles.colorRow}>
                    <input id="ev-theme-surface" type="color" value={form.themeSurface || '#f7f2e8'} onChange={(e) => setForm({ ...form, themeSurface: e.target.value === '#f7f2e8' ? '' : e.target.value })} />
                    <input value={form.themeSurface} onChange={(e) => setForm({ ...form, themeSurface: e.target.value })} placeholder="#f7f2e8" />
                  </div>
                </div>
                <div className={styles.field}>
                  <label htmlFor="ev-theme-highlight">Colore accento</label>
                  <div className={styles.colorRow}>
                    <input id="ev-theme-highlight" type="color" value={form.themeHighlight || '#f4c978'} onChange={(e) => setForm({ ...form, themeHighlight: e.target.value === '#f4c978' ? '' : e.target.value })} />
                    <input value={form.themeHighlight} onChange={(e) => setForm({ ...form, themeHighlight: e.target.value })} placeholder="#f4c978" />
                  </div>
                </div>
              </div>
            </fieldset>

            <fieldset className={styles.fieldset}>
              <legend className={styles.legend}>Immagini</legend>
              <ImageUploader
                mode="single"
                type="event"
                value={form.coverImage}
                onChange={(data) => setForm({ ...form, coverImage: data as UploadedImage | null })}
                label="Immagine di copertina"
              />
              <ImageUploader
                mode="single"
                type="event"
                value={form.logo}
                onChange={(data) => setForm({ ...form, logo: data as UploadedImage | null })}
                label="Logo"
              />
              <ImageUploader
                mode="multiple"
                type="event"
                value={form.gallery}
                onChange={(data) => setForm({ ...form, gallery: data as UploadedImage[] })}
                label="Galleria"
              />
            </fieldset>

            <div className={styles.formActions}>
              <button type="submit" className={styles.primaryBtn}>
                {editingId ? 'Salva modifiche' : 'Crea evento'}
              </button>
              <button type="button" className={styles.secondaryBtn} onClick={() => setShowForm(false)}>
                Annulla
              </button>
            </div>
          </form>
        )}

        <div className={styles.list}>
          {events.map((ev) => (
            <article key={ev.id} className={styles.card}>
              <div className={styles.cardBody}>
                <strong className={styles.cardName}>{ev.name}</strong>
                <span className={styles.cardDate}>{fmtDate(ev.startDate)} &ndash; {fmtDate(ev.endDate)}</span>
                <span className={styles.cardLocation}>{ev.location.label}</span>
                {ev.shortDescription && <span className={styles.cardDesc} dangerouslySetInnerHTML={{ __html: ev.shortDescription }} />}
              </div>
              <div className={styles.cardActions}>
                <Link className={styles.textBtn} to={`/events/${ev.id}`}>
                  Vedi
                </Link>
                <button
                  className={`${styles.favBtn} ${favoriteIds.has(ev.id) ? styles.favBtnActive : ''}`}
                  onClick={() => toggleFavorite(ev.id)}
                  aria-label={favoriteIds.has(ev.id) ? 'Rimuovi dai preferiti' : 'Aggiungi ai preferiti'}
                >
                  {favoriteIds.has(ev.id) ? '\u2764' : '\u2661'}
                </button>
                <button className={styles.textBtn} onClick={() => openEdit(ev)}>
                  Modifica
                </button>
                <button className={styles.textBtn} onClick={() => setExpandedEventId(expandedEventId === ev.id ? null : ev.id)}>
                  {expandedEventId === ev.id ? 'Chiudi stand' : 'Stand'}
                </button>
                <button className={styles.dangerBtn} onClick={() => setDeleteConfirmId(ev.id)}>
                  Elimina
                </button>
              </div>
              {expandedEventId === ev.id && (
                <div className={styles.standManager}>
                  {standList.length === 0 && <span className={styles.emptyStands}>Nessuno stand disponibile.</span>}
                  {standList.map((stand) => {
                    const isLinked = stand.eventIds.includes(ev.id)
                    const isSaving = savingStands.has(stand.id)
                    return (
                      <label key={stand.id} className={`${styles.standCheckbox} ${isLinked ? styles.standLinked : ''}`}>
                        <input
                          type="checkbox"
                          checked={isLinked}
                          disabled={isSaving}
                          onChange={() => handleToggleStand(stand.id, ev.id, isLinked)}
                        />
                        {stand.name}
                      </label>
                    )
                  })}
                </div>
              )}
            </article>
          ))}

          {events.length === 0 && (
            <p className={styles.empty}>Nessun evento. Creane uno nuovo.</p>
          )}
        </div>
      </div>

      <ConfirmModal
        open={deleteConfirmId !== null}
        variant="confirm"
        title="Elimina evento"
        message={`Sei sicuro di voler eliminare questo evento? L'operazione non può essere annullata.`}
        confirmLabel="Elimina"
        danger
        onConfirm={handleDelete}
        onCancel={() => setDeleteConfirmId(null)}
      />

      <ConfirmModal
        open={alertMsg !== null}
        variant="alert"
        title="Attenzione"
        message={alertMsg ?? ''}
        confirmLabel="OK"
        onConfirm={() => setAlertMsg(null)}
        onCancel={() => setAlertMsg(null)}
      />
    </div>
  )
}
